# https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
# version: "3.9"  
services:
  grafana:
    container_name: ndac_grafana
    image: ndac_grafana
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana_storage:/var/lib/grafana
      - ./grafana_data/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana_data/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana_data/dashboards:/etc/grafana/dashboards
  
  nginx:
    container_name: ndac_nginx
    image: ndac_nginx
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=172.17.0.1
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana